# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Registerly

on:
  push:
    branches: [ "master" ]
    paths: [ "Registerly" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "Registerly" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: |
         chmod +x ./Registerly/build.sh
         cd ./Registerly/
         ./build.sh
      shell: bash
    - name: Get version
      id: get-version
      uses: kzrnm/get-net-sdk-project-versions-action@v2
      with:
        proj-path: ./Registerly/src/DeviantCoding.Registerly.csproj
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeviantCoding.Registerly.${{ steps.get-version.outputs.version }}_${{ steps.date.outputs.date }}.${{ github.run_number }}.${{ github.run_attempt }}
        path: ${{ github.workspace }}/Registerly/src/bin/Release/*.nupkg
