# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Registerly
concurrency: integration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
        default: 'NUGETTEST.ORG'
      tag:
        description: 'Release Tag to deploy'
        required: true
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4    
    - name: Get package
      env:  
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}
        tag: ${{ inputs.tag }}
      run: |
        gh release download "${{ env.tag }}"
      shell: bash
    - name: Publish to nuget.org
      run: dotnet nuget push ./*.nupkg --api-key ${{ secrets.NUGETORG_APIKEY }} --source ${{ vars.NUGETORG_URL }} 
