# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: |
         chmod +x ./Registerly/build.sh
         cd ./Registerly/
         ./build.sh
         pwd
      shell: bash
    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: DeviantCoding.Registerly.${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
        path: src/bin/Release/*.nupkg
